name: Deploy to github pages
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 12.x
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Clean install dependencies
      run: npm ci
    - name: Run deploy script
      run: |
        git config user.name "aotearoan" && git config user.email "andrew@aotearoan.com"
        npm run gh-pages-deploy
